---
- name: Check if local folder storage exists
  ansible.builtin.file:
    path: "{{ storage_folder.path }}/{{ storage_type }}/{{ group_names[0] }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Copy file to local folder storage
  delegate_to: localhost
  ansible.builtin.copy:
    src: "{{ storage_src }}"
    dest: "{{ storage_folder.path }}/{{ storage_type }}/{{ group_names[0] }}/{{ storage_src | basename }}"
    mode: '0755'