---
- name: Telegram report
  ansible.builtin.include_tasks: includes/telegram.yml
  when:
    - report_telegram.is_enabled|bool

- name: Email report
  ansible.builtin.include_tasks: includes/email.yml
  when:
    - report_email.is_enabled|bool
