---
# TODO Email message format
- name: Backup RouterOS Configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Upgrade
      include_role:
        name: upgrade
      vars:
        upgrade_type: "{{ type }}"
    # Only for Check Last Release, for single notify
    - name: Report
      run_once: true
      include_role:
        name: report
      vars:
        report_html_message_text: "{{ upgrade_release_notes_message }}"
      when:
        - type == "check_last_release"