---
- name: Parse MikroTik RouterOS latest stable RSS feed
  hosts: localhost
  gather_facts: no
  vars:
    rss_url: "https://download.mikrotik.com/routeros/latest-stable.rss"
    content_encoded: "http://purl.org/rss/1.0/modules/content/"
    update_common_types:  ['check_last_release', 'firmware']

  tasks:
    - name: Validate type
      ansible.builtin.assert:
        that:
          - update_type in update_common_types
        fail_msg: "Invalid backup_type: {{ update_type }}. Must be one of {{ update_common_types }}."
        success_msg: "Type {{ update_type }} is valid."

    - name: Fetch RSS feed
      uri:
        url: "{{ rss_url }}"
        return_content: yes
        status_code: 200
      register: rss_response

    - name: Write RSS content to a temporary file (for xml module)
      set_fact:
        xml_content: "{{ rss_response.content }}"
      delegate_to: localhost
      run_once: yes

    - name: Get title from xml.
      xml:
        xmlstring: "{{ xml_content }}"
        content: "text"
        xpath: "/rss/channel/item/title"
      register: xml_item_title

    - name: Get link from xml.
      xml:
        xmlstring: "{{ xml_content }}"
        content: "text"
        xpath: "/rss/channel/item/link"
      register: xml_item_link

    - name: Get content from xml.
      xml:
        xmlstring: "{{ xml_content }}"
        content: "text"
        xpath: "/rss/channel/item/content:encoded"
        namespaces:
          content: "http://purl.org/rss/1.0/modules/content/"
      register: xml_item_content

    - name: Get title, link, and description from first item
      set_fact:
        item_title: "{{ xml_item_title.matches[0].title | default('N/A') }}"
        item_link: "{{ xml_item_link.matches[0].link | default('N/A') }}"
        item_content: "{{ xml_item_content.matches[0]['{http://purl.org/rss/1.0/modules/content/}encoded'] | default('N/A') }}"

    - name: rss-item-vars
      debug:
        msg:
          - "{{ item_title }}"
          - "{{ item_link }}"
          - "{{ item_content }}"