---

- name: Dump RouterOS Configuration
  hosts: all
  serial: 1
  connection: network_cli
  gather_facts: false
  roles:
    - role: backup
  vars_files:
    - "./roles/backup/vars/backup-action-defaults.yml"
