---
- name: Export RouterOS Configuration
  hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  roles:
    - role: backup
  vars_files:
    - "./roles/backup/vars/export-action-defaults.yml"
