---
- name: Install requirements
  hosts: localhost
  tasks:
    - name: Install curl, gpg, paramiko
      delegate_to: localhost
      ansible.builtin.apt:
        name:
          - curl
          - gpg
          - python3-paramiko
        state: present
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian"
