---
- name: Debug errors result
  uri:
    url: "https://api.telegram.org/bot{{ backup_telegram.bot_token }}/sendMessage"
    method: POST
    body_format: json
    body:
      chat_id: "{{ backup_telegram.chat_id }}"
      text: "Ошибка: {{ ansible_failed_result.msg }}"
      message_thread_id: "{{ backup_telegram.message_thread_id | default(omit) }}"
  delegate_to: localhost
