---
- name: Send backup file to Telegram
  ansible.builtin.command: >
    curl -s -X POST "https://api.telegram.org/bot{{ telegram_bot_token }}/sendDocument"
    -F chat_id="{{ telegram_chat_id }}"
    -F message_thread_id="{{ telegram_message_thread_id | default(omit) }}"
    -F document=@"{{ full_export_path }}"
    -F caption="#{{ type }} {{ identity }}"
  delegate_to: localhost
  when: encrypt_with_gpg|bool == False

- name: Send encrypted backup file to Telegram
  ansible.builtin.command: >
    curl -s -X POST "https://api.telegram.org/bot{{ telegram_bot_token }}/sendDocument"
    -F chat_id="{{ telegram_chat_id }}"
    -F message_thread_id="{{ telegram_message_thread_id | default(omit) }}"
    -F document=@"{{ full_export_path }}.asc"
    -F caption="#{{ type }} {{ identity }}"
  delegate_to: localhost
  when: encrypt_with_gpg|bool == True and gpg_key_email | length > 0

- name: Pause for {{ pause_between_messages}} seconds
  pause:
    seconds: "{{ pause_between_messages }}"
  with_items:
    - "{{ pause_between_messages }}"
