---
- name: Generate out_folder_name
  ansible.builtin.set_fact:
    out_folder_name: "{{ out_root }}/{{ export_dir }}/{{ group_name_dir }}"
  when: export_dir is defined and export_dir | length > 0
  delegate_to: localhost

- name: Get current datetime
  ansible.builtin.set_fact:
    current_datetime: "{{ now(utc=false,fmt='%Y-%m-%d-%H-%M-%S') }}"
  delegate_to: localhost

- name: Create out dir if not exists
  ansible.builtin.file:
    path: "{{ out_folder_name }}"
    state: directory
  delegate_to: localhost
  when: out_folder_name is defined and out_folder_name | length > 0
  become: false

- name: Generate full export path
  ansible.builtin.set_fact:
    full_export_path: "{{ out_folder_name }}/{{ current_datetime }}-{{ identity }}-{{ inventory_hostname }}.{{ backup_extension }}"
  delegate_to: localhost
  when: out_folder_name is defined and out_folder_name | length > 0
