---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  vars_files:
    - "./vars/01-backup-export-vars.yml"
  tasks:
    # TODO one action except any
    - name: Set export_dir path
      ansible.builtin.set_fact:
        export_dir: "export"
      when: action == "export"
    
    - name: Set export_dir path
      ansible.builtin.set_fact:
        export_dir: "dump"
      when: action == "backup"

    - name: Get out_folder_name
      ansible.builtin.set_fact:
        out_folder_name: "{{ out_root }}/{{ export_dir }}/{{ group_name_dir }}"
      when: export_dir is defined and export_dir | length > 0
      delegate_to: localhost
    
    - name: Get current datetime
      ansible.builtin.set_fact:
        current_datetime: "{{ now(utc=false,fmt='%Y-%m-%d-%H-%M-%S') }}"
      delegate_to: localhost
