---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Create out dir if not exists
      ansible.builtin.file:
        path: "{{ out_folder_name }}"
        state: directory
      delegate_to: localhost
      when: out_folder_name is defined and out_folder_name | length > 0
      become: false
