---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Get current datetime
      ansible.builtin.set_fact:
        current_datetime: "{{ now(utc=false,fmt='%Y-%m-%d-%H-%M-%S') }}"
      delegate_to: localhost

    - name: Create export on RouterOS Device
      routeros_command:
        commands:
          - /export show-sensitive terse file={{ identity }}

    - name: Get full export path
      ansible.builtin.set_fact:
        full_export_path: "{{ out_folder_name }}/{{ current_datetime }}-{{ identity }}-{{ inventory_hostname }}.rsc"
      delegate_to: localhost
      when: out_folder_name is defined and out_folder_name | length > 0
    
    - name: Get export file
      ansible.netcommon.net_get:
        src: "{{ identity }}.rsc"
        dest: "{{ full_export_path }}"
        protocol: sftp
      when: full_export_path is defined and full_export_path | length > 0
