---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  vars_files:
    - "./vars/02-{{ action }}-action-defaults.yml"
  tasks:
    - name: Create full binary backup dump on RouterOS Device
      routeros_command:
        commands:
          - /system backup save name={{ identity }} password={{ identity }}
      when: action == "backup"

    - name: Create export on RouterOS Device
      routeros_command:
        commands:
          - /export show-sensitive terse file={{ identity }}
      when: action == "export"
    
    - name: Get export file
      ansible.netcommon.net_get:
        src: "{{ identity }}.{{ backup_extension }}"
        dest: "{{ full_export_path }}"
        protocol: sftp
      when: full_export_path is defined and full_export_path | length > 0
