---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  vars_files:
    - "./vars/01-group-defaults.yml"
    - "./vars/02-{{ type }}-action-defaults.yml"

  tasks:

    - name: Create full binary backup dump on RouterOS Device
      routeros_command:
        commands:
          - /system backup save name={{ identity }}
      when: type == "backup"

    - name: Create export on RouterOS Device
      routeros_command:
        commands:
          - /export  {% if export_is_sensitive | default(false) %}show-sensitive terse{% endif %} file={{ identity }}
      when: type == "export"
    
    - name: Get export file
      ansible.netcommon.net_get:
        src: "{{ identity }}.{{ backup_extension }}"
        dest: "{{ full_export_path }}"
        protocol: sftp
      when: full_export_path is defined and full_export_path | length > 0
