---
- hosts: ALL_RouterOS
  connection: network_cli
  gather_facts: false
  vars_files:
    - "./vars/01-group-defaults.yml"

  tasks:

    - name: Send backup file to Telegram
      ansible.builtin.command: >
        curl -s -X POST "https://api.telegram.org/bot{{ telegram_bot_token }}/sendDocument"
        -F chat_id="{{ telegram_chat_id }}"
        {% if telegram_message_thread_id is defined %}-F message_thread_id="{{ telegram_message_thread_id }}"{% endif %}
        -F document=@"{{ full_export_path }}"
        -F parse_mode="Markdown"
        -F caption="{{ identity }}"
      delegate_to: localhost
      when: encrypt_with_gpg|bool == False
    
    - name: Send encrypted backup file to Telegram
      ansible.builtin.command: >
        curl -s -X POST "https://api.telegram.org/bot{{ telegram_bot_token }}/sendDocument"
        -F chat_id="{{ telegram_chat_id }}"
        {% if telegram_message_thread_id is defined %}-F message_thread_id="{{ telegram_message_thread_id }}"{% endif %}
        -F document=@"{{ full_export_path }}.asc"
        -F parse_mode="Markdown"
        -F caption="{{ identity }}"
      delegate_to: localhost
      when: encrypt_with_gpg|bool == True and gpg_key_email | length > 0
