---
- name: Get identity from RouterOS device
  routeros_command:
    commands: /system identity print
  register: dev_identity

- name: Get identity from string
  ansible.builtin.set_fact:
    identity: "{{ dev_identity.stdout_lines[0][0] | replace('name: ', '') }}"
  when: dev_identity is defined and dev_identity | length > 0
  delegate_to: localhost
