---
- name: Remove file from RouterOS Device
  routeros_command:
    commands:
      - /file remove {{ identity }}.{{ backup_extension }}
  when: identity is defined and identity | length > 0

- name: Search backups older than backup retention days
  find:
    paths: "{{ out_folder_name }}"
    age: "{{ retention_policy }}"
  register: backups_to_clear
  when: retention_policy is defined and retention_policy | length > 0

- name: Removing older backups
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ backups_to_clear.files }}"
  when: backups_to_clear is defined and backups_to_clear | length > 0
