---
- name: Check git storage folder exists
  ansible.builtin.file:
    path: "{{ transport_git.path }}/{{ group_names[0] }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Get unencrypted export file name for git
  ansible.builtin.set_fact:
    transport_git_src: "{{ transport_src | regex_replace('.asc$', '') }}"
  delegate_to: localhost

- name: Copy file to git folder storage
  delegate_to: localhost
  ansible.builtin.copy:
    src: "{{ transport_git_src }}"
    dest: "{{ transport_git.path }}/{{ group_names[0] }}/{{ inventory_hostname }}/{{ transport_git_src | basename }}"
    mode: '0755'
    force: true

- name: "Init git repository"
  ansible.builtin.shell: >
    test -d .git || git init
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost

- name: "Git set branch"
  ansible.builtin.shell: >
    git branch -M {{ transport_git.branch | default('main') }}
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost
  register: transport_branch_rename_result
  failed_when: false

- name: "Git add origin"
  ansible.builtin.shell: >
    git remote add origin {{ transport_git.repository_url }}
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost
  failed_when: false
  when:
    - transport_git.repository_url is defined

- name: "Git add to tracking"
  ansible.builtin.shell: >
    git add .
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost
  failed_when: false

- name: Check if there are git changes
  ansible.builtin.shell: git diff --quiet HEAD
  args:
    chdir: "{{ transport_git.path }}"
  register: transport_git_diff
  delegate_to: localhost
  failed_when: false
  changed_when: false

- name: "Git commit changes"
  ansible.builtin.shell: >
    git commit -m "{{ transport_git_src | basename }} {{ inventory_hostname }} $(date +"%Y-%m-%d %H:%M:%S")"
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost
  when:
    - transport_git_diff.rc == 1

- name: "Git push changes"
  ansible.builtin.shell: >
    git push -u origin {{ transport_git.branch | default('main') }}
  args:
    chdir: "{{ transport_git.path }}"
  delegate_to: localhost
  when:
    - transport_git.repository_url is defined
    - transport_git_diff.rc == 1
