---

- name: Storage FTP module
  ansible.builtin.include_tasks: includes/ftp.yml

- name: Storage Local folder module
  ansible.builtin.include_tasks: includes/local-folder.yml

- name: Storage Git module
  ansible.builtin.include_tasks: includes/git.yml
