---
backup_telegram:
  pause_between_messages: 5

backup_storage:
  out_root: ../out
  group_name_dir: "ungrouped"
  retention_policy: "7d"

backup_export_config:
  is_sensitive: false

backup_binary_dump:
  is_encrypted: true

backup_encryption:
  is_enabled: false
